FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

RUN addgroup -S app && adduser -S -G app app

COPY --chown=app:app application.jar /app/application.jar

USER app
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/application.jar"]
