spring:
  application:
    name: employee-lifecycle-sync
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_lifecycle_sync}
    username: ${DB_USERNAME:employee_sync}
    password: ${DB_PASSWORD:employee_sync_local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
