CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(64) NOT NULL,
    name VARCHAR(200) NOT NULL,
    company_email VARCHAR(320),
    department_code VARCHAR(100),
    employment_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_employee_employee_no UNIQUE (employee_no),
    CONSTRAINT ck_employee_employment_status
        CHECK (employment_status IN ('ACTIVE', 'ON_LEAVE', 'TERMINATED'))
);
