CREATE TABLE sync_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    total_count INTEGER NOT NULL,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    CONSTRAINT ck_sync_job_status
        CHECK (status IN ('RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED')),
    CONSTRAINT ck_sync_job_counts_nonnegative
        CHECK (total_count >= 0 AND inserted_count >= 0 AND updated_count >= 0
            AND skipped_count >= 0 AND failed_count >= 0)
);

CREATE TABLE sync_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_job_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    employee_no TEXT,
    result VARCHAR(20) NOT NULL,
    error_code TEXT,
    error_message TEXT,
    employee_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_sync_item_sync_job
        FOREIGN KEY (sync_job_id) REFERENCES sync_job (id),
    CONSTRAINT fk_sync_item_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT uk_sync_item_job_row UNIQUE (sync_job_id, row_number),
    CONSTRAINT ck_sync_item_row_number CHECK (row_number > 0),
    CONSTRAINT ck_sync_item_result
        CHECK (result IN ('INSERTED', 'UPDATED', 'SKIPPED', 'FAILED')),
    CONSTRAINT ck_sync_item_employee_link
        CHECK (
            (result IN ('INSERTED', 'UPDATED', 'SKIPPED') AND employee_id IS NOT NULL)
            OR (result = 'FAILED' AND employee_id IS NULL)
        )
);
