CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    sync_item_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    changes TEXT NOT NULL,
    source VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_audit_log_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_audit_log_sync_item
        FOREIGN KEY (sync_item_id) REFERENCES sync_item (id),
    CONSTRAINT uk_audit_log_sync_item UNIQUE (sync_item_id),
    CONSTRAINT ck_audit_log_action CHECK (action IN ('CREATED', 'UPDATED')),
    CONSTRAINT ck_audit_log_source CHECK (source IN ('HR_SYNC'))
);

CREATE INDEX ix_audit_log_employee_created_at ON audit_log (employee_id, created_at);

CREATE TABLE integration_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    sync_item_id BIGINT NOT NULL,
    target VARCHAR(20) NOT NULL,
    action VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payload TEXT NOT NULL,
    idempotency_key UUID NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_count INTEGER NOT NULL DEFAULT 3,
    next_retry_at TIMESTAMPTZ,
    last_error_code TEXT,
    last_error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_integration_task_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_integration_task_sync_item
        FOREIGN KEY (sync_item_id) REFERENCES sync_item (id),
    CONSTRAINT uk_integration_task_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uk_integration_task_sync_item_target UNIQUE (sync_item_id, target),
    CONSTRAINT ck_integration_task_target CHECK (target IN ('GROUPWARE')),
    CONSTRAINT ck_integration_task_action
        CHECK (action IN ('CREATE_ACCOUNT', 'UPDATE_ACCOUNT', 'DISABLE_ACCOUNT')),
    CONSTRAINT ck_integration_task_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_WAIT', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_integration_task_retry_counts
        CHECK (retry_count >= 0 AND max_retry_count >= 0 AND retry_count <= max_retry_count)
);
