CREATE TABLE integration_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integration_task_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    result VARCHAR(20) NOT NULL,
    http_status INTEGER,
    error_code TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_integration_attempt_task
        FOREIGN KEY (integration_task_id) REFERENCES integration_task (id),
    CONSTRAINT uk_integration_attempt_task_attempt_no UNIQUE (integration_task_id, attempt_no),
    CONSTRAINT ck_integration_attempt_number CHECK (attempt_no > 0),
    CONSTRAINT ck_integration_attempt_result CHECK (result IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_integration_attempt_time CHECK (finished_at >= started_at),
    CONSTRAINT ck_integration_attempt_result_details CHECK (
        (result = 'SUCCESS' AND error_code IS NULL AND error_message IS NULL)
        OR (result = 'FAILED' AND error_code IS NOT NULL AND error_message IS NOT NULL)
    )
);

CREATE INDEX ix_integration_attempt_task_created_at
    ON integration_attempt (integration_task_id, created_at);
